# Generated by Django 3.1.6 on 2021-02-01 20:48

from django.db import migrations


def add_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Teacher = apps.get_model("app_hw_12", "Teacher")
    for teacher in Teacher.objects.all():
        teacher.first_name = "%s %s" % (teacher.first_name, teacher.last_name)
        teacher.save()
    Student = apps.get_model("app_hw_12", "Student")
    for student in Student.objects.all():
        student.first_name = "%s %s" % (student.first_name, student.last_name)
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app_hw_12", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
